### ISSUE TITLE
Contact SarthakJariwala and coordinate efforts, give credit. 

### ISSUE THREAD

**Issue by jaustinpage** [jaustinpage/pyscaffoldext-nox#11]
I made a mistake. When I started down the path of making a nox plug-in for pyscaffold, I first searched pypi for a plug-in to use, assuming that someone had already made one. Seeing none, I assumed nobody had worked on one. So, created this repo, made the plug-in, and pushed it to pypi. 

When I felt I had something worth sharing, I figured I would post to the pyscaffold community or to the nox community to see if there was community interest in the plug-in. That's when I learned about @SarthakJariwala and his efforts to make a nox plug-in for pyscaffold, through the issue  https://github.com/pyscaffold/pyscaffold/issues/287 and their plug-in efforts here: https://github.com/SarthakJariwala/pyscaffoldext-nox to create a nox plug in.

I would not have registered the pypi package if I had known of the prior effort to make a plug in, especially after seeing the discourse on the topic by the community already. 

I welcome well-intentioned discussion on what I should do, especially if @SarthakJariwala has any opinions. Feel free to reach out publicly or privately.

**Comment by SarthakJariwala** [comment]
Thanks for reaching out @jaustinpage. Nothing wrong on your end :-)

The extension was almost ready a while back, but I didn't push it to PyPI. I haven't worked on the extension for almost two years (I have switched to a poetry-based workflow for python package but still use pyscaffold for my data science projects) and pyscaffold has undergone some changes during that time, so it might not be compatible with the new API changes. I haven't tested it though.

If you find parts of my code useful, please feel free to use them. The project is permissively licensed (MIT). If you feel your project is ready, I am happy to archive mine and link people to the extension you are developing.

I think it would be great to have a nox extension for pyscaffold.

**Comment by jaustinpage** [comment]
I am keeping MIT licensing for this plugin. 

In general, I was working to get parity with tox for the noxfile.py, there are admittedly a few extras in the noxfile that probably are a bit overboard. I should probably see if they belong in mainline nox. 

I think this one is ready... It would be a delight to see if it works for others.

**Comment by jaustinpage** [comment]
I'll leave the question of archiving and linking up to you, I welcome it but only if you feel this is good enough to warrant it.
